name: Category Service Deployment Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'PersonalFinanceTracker/category/**'

env:
  SQS_QUEUE_NAME: ${{ secrets.SQS_QUEUE_NAME }}

jobs:
  CategoryBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

          IMAGE_NAME=finance_tracker_category_service:0.0.${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          