name: Personal Finance Tracker Service Deployment Dev

on:
  push:
    branches:
      - dev

env:
  SQS_QUEUE_NAME: ${{ secrets.SQS_QUEUE_NAME }}



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if app.py was modified
      id: changes
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'PersonalFinanceTracker/app.py' || echo "no-match"
    
    - name: Conditional step if app.py is changed
      if: steps.changes.outputs.result != 'no-match'
      run: echo "PersonalFinanceTracker/app.py was modified!"

# jobs:
#   FinanceBuild:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repo code
#         uses: actions/checkout@v2

#       - name: Build and push image
#         run: |
#           docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

#           IMAGE_NAME=finance_tracker:0.0.${{ github.run_number }}
#           docker build -t $IMAGE_NAME .
#           docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
#           docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          